#!/usr/bin/env bash
# This script answers the questions about UDP and TCP.

# Question 1
echo "It is a protocol that is transferring data in a slow way but surely"

# Question 2
echo "It is a protocol that is transferring data in a fast way and might lose data along the way"

# Question 3
echo "May I increase the rate at which I am sending you boxes?"

