#!/bin/bash

# Enable debugging
set -x

# Check if nginx is running
if ! systemctl is-active --quiet nginx; then
  echo "Starting Nginx service..."
  systemctl start nginx
fi

# Check if Nginx is listening on port 80 for all IPv4 addresses
active_ipv4_addresses=$(ip -4 addr show | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -Eo '[^/]+$')

for address in $active_ipv4_addresses; do
  if ! netstat -tlpn | grep ":80" | grep -q "$address"; then
    echo "Nginx not listening on port 80 for address $address. Fixing..."
    sed -i "s/listen       80 default_server;/listen       80 $address default_server;/g" /etc/nginx/sites-available/default
    systemctl reload nginx
  fi
done
