#!/usr/bin/env bash
# This script configures the local host file to change the IP resolution of localhost and facebook.com.

# Change localhost resolution to 127.0.0.2
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Change facebook.com resolution to 8.8.8.8
sudo sed -i 's/157.240.11.35/8.8.8.8/g' /etc/hosts

